[profile.default]
# grant access to the deployment addresses for the registry test:
fs_permissions = [{ access = "read", path = "./node_modules/@jbx-protocol/juice-delegates-registry/broadcast/Deploy.s.sol"}]
libs = ['lib', 'node_modules']
out = 'out'
src = 'contracts'
test = 'forge-test'
script = 'scripts'
gas_reports_ignore = [
    "JBTokenStore",
    "JBSplitsStore",
    "JBSingleTokenPaymentTerminalStore",
    "JBProjects",
    "JBFundingCycleStore",
    "JBETHPaymentTerminal",
    "JBDirectory",
    "JBController",
    "AccessJBLib",
    "JBIpfsDecoder",
    "ForTest_JBTiered721Delegate",
    "ForTest_JBTiered721DelegateStore",
    "JBTiered721DelegateStore",
]
remappings = [
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
]

optimizer_runs = 200

block_timestamp = 1674745056

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
