[default]
src = 'contracts'
test = 'test'
out = 'out'
libs = ['lib']
remappings = [
    'ds-test/=lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
]
libraries = []
cache = true
force = false
evm_version = 'london'
gas_reports = ['*']
auto_detect_solc = true
optimizer = true
optimizer_runs = 10000000
fuzz_runs = 1024
initial_balance = '0xffffffffffffffffffffffff'
block_number = 14126430
block_timestamp = 1643802347
